language: python
python:
  - 2.7
install:
  - pip install -r requirements.txt
  - pip install coveralls
  - pip install coverage
  - pip install pytest pytest-cov
script:
  - pytest --cov=app/api app/tests/

after_success:
  - coveralls