language: python
python:
  - 3.6
install:
  - pip install -r requirements.txt
  - pip install coveralls
  - pip install coverage
  - pip install pytest pytest-cov
script:
  - pytest --cov=app/api/v2 app/tests/v2

after_success:
  - coveralls